name: Main workflow

on: [push, workflow_dispatch]

permissions: read-all

jobs:
  build-solution:
    name: Build solution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Build application project
        run: |
          docker build \
            --file ./Source/MusicLibrarySuite.Application/Dockerfile \
            --build-arg NuGetUsername=AndreyTalanin \
            --build-arg NuGetClearTextPassword=${{ secrets.GITHUB_TOKEN }} \
            ./Source
